add missing libintl.h includes for gettext() and friends
using a distro based on musl libc, i got these error messages:
src/window.cpp:36:16: error: 'gettext' was not declared in this scope
...